package network.network_Client;



/**
 * This listener receive command events which
 * are fired by CaffeineClient.
 * @author Romain Guy
 */

public interface NetworkListener
{
  /**
   * Any class implemeting this will receive all the
   * messages from the server in this method. The Object
   * is generated by the filters.
   * @param evt The <code>NetworkEvent</code> received from server
   */

  public abstract void networkEvent(NetworkEvent evt);
  
  public abstract void networkDisconnected(String string);
}