package com.gmo.processorNode.viewmodel.analyses.standard;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.gmo.processorNode.viewmodel.ViewCreateProcessConfiguration;
import com.gmo.sharedobjects.model.analysis.AnalysisStatus;
import com.gmo.sharedobjects.model.reports.Report;


public class ViewAnalysis {
	
	private String id;
	
	private String userid;

	// Configuration generated by the view
	private ViewCreateProcessConfiguration viewConfiguration;
	
	private long launchDate;

	private long completionDate;
	
	private final static DateFormat df = new SimpleDateFormat("dd-MM-yyyy HH:mm");
	
	private AnalysisStatus status;
	
	// Associated report
	private Report report;
	
	public long getLaunchDate() {
		return launchDate;
	}

	public void setLaunchDate(long laundDate) {
		this.launchDate = laundDate;
	}

	public String getLaunchDateFormat() {
		return df.format(new Date(launchDate));
	}

	public void setLaunchDateFormat(String laundDateFormat) {
	}

	public long getCompletionDate() {
		return completionDate;
	}

	public void setCompletionDate(long endDate) {
		this.completionDate = endDate;
	}

	public String getCompletionDateFormat() {
		return df.format(new Date(completionDate));
	}
	
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserid() {
		return userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}
	
	public AnalysisStatus getStatus() {
		return status;
	}

	public synchronized void setStatus(AnalysisStatus newstatus) {
		this.status = newstatus;
	}
	
	public Report getReport() {
		return report;
	}

	public void setReport(Report report) {
		this.report = report;
	}

	public ViewCreateProcessConfiguration getViewConfiguration() {
		return viewConfiguration;
	}

	public void setViewConfiguration(ViewCreateProcessConfiguration viewConfiguration) {
		this.viewConfiguration = viewConfiguration;
	}
	
	

}
