package processorNode.viewmodel.analyses.standard;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import processorNode.viewmodel.ViewCreateProcessConfiguration;


public class ViewAnalysis {
	
	private String id;
	
	private String userid;

	// Configuration generated by the view
	private ViewCreateProcessConfiguration viewConfiguration;
	
	private long launchDate;

	private long completionDate;
	
	private final static DateFormat df = new SimpleDateFormat("dd-MM-yyyy HH:mm");
	
	public String getLaunchDateFormat() {
		return df.format(new Date(launchDate));
	}

	public void setLaunchDateFormat(String laundDateFormat) {
	}

	public long getCompletionDate() {
		return completionDate;
	}

	public void setCompletionDate(long endDate) {
		this.completionDate = endDate;
	}

	public String getCompletionDateFormat() {
		return df.format(new Date(completionDate));
	}
	
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserid() {
		return userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

}
